### PR TITLE
Add a basic VSCode configuration for probe-rs-debugger

### LINKED ISSUE #26: Debug support via probe-rs-debugger
I'm trying to set up probe-rs-debugger with VSCode to easily set breakpoints and debug my program. Would it be possible for a probe-rs-debugger config to be created for this template?

### PR DESCRIPTION
**Pull request by 9names**
Closes #26

### CODE REVIEW

**Comment by 9names** [comment]
This should partially address #16 as well

**Comment by UnicornsOnLSD** [comment]
This works for the most part. The issues I had were:

* The task does not build the program
* The task uses a release build, which isn't suitable for debugging
* Debug builds build with an `opt-level` of 3 by default, which doesn't work with breakpoints
* I wasn't able to inspect variables when stepping through
* When stepping to the next line the Pi wouldn't halt again

Most of these issues are presumably related to `probe-rs`.

**Comment by 9names** [comment]
> The task does not build the program

Ah, we need a build task and a pre-launch step in this script.

> The task uses a release build, which isn't suitable for debugging.

Rust code really benefits a lot from optimisation, and since interactive debugging options were limited (and most folks just used rtt or defmt printing for debugging) the defaults in the template were set to high optimisations for both release and debug builds. 
The current optimisation level will limit how much can be inspected, maybe we can use the debug build and lower optimisation a bit.

> Most of these issues are presumably related to probe-rs.

No, I think everything you listed sounds like it's related to optimisation level

**Comment by UnicornsOnLSD** [comment]
Even with the optimisation level set to 0 I was still unable to inspect variables

**Comment by 9names** [comment]
I assume based on the feedback given that this PR is sufficient to get started, please add more comments or create github issues if you have more problems

**Comment by jhodapp** [comment]
> I can inspect the value of static bindings, but those are the easiest thing for the debugger to handle The single-stepping issue is something I've seen mentioned as a probe-rs issue? So we're probably stuck with that. It at least builds and runs now, plus we get defmt print messages again so it's on par with what we get from the other debug options.

I'm seeing the same thing applied to [my project here](https://github.com/Jim-Hodapp-Coaching/esp32-pico-wifi/pull/21). It's somewhat useful as in I can set a breakpoint in my main.rs and it breaks and I can see variables in scope, but it's not a good experience to step through code at all.

I also modified it to point to my existing build task, otherwise it didn't build by default as the default example doesn't point to a build task I have defined by default.

**Comment by cstrahan** [comment]
Anyone know if this is an issue that should be taken up with `probe-rs`, or if this is a just a matter of extra config being needed/tweaked? I'll open an issue in `probe-rs` if needed -- just not sure on which side of the fence this issue rests.

**Comment by 9names** [comment]
Sorry,  which issue are you referring to?

**Pull request merged**
